#17 패들에 따른 각도변화
konkuk-galaxy/frontend pull request #22
Opened 2023-05-20 06:20 UTC by Jiwoo-Seo

## 패들 맞는 부위에 따른 각도변화

2023-05-21 06:04 UTC, kth990303 requested changes
각도 변화되는 거 확인했습니다~
개인적인 바람 몇가지 코멘트 남겨봤는데, 맘에 드시면 반영해주시고 아니면 놔두셔도 괜찮을 것 같아요~
확인 후 다시 리뷰요청해주시면 approve하겠습니다

2023-05-21 06:04 UTC, kth990303 commented on game ver.commit 1.js
> +            }
혹시 여기만 0.95 + 각도 불변인 이유가 있을까요? 1.00으로 해서 동일하게 나아가더라도, 패들의 다른 부분에 맞으면 문제없이 게임이 잘 흘러갈 거 같아서요!

2023-05-21 06:04 UTC, kth990303 commented on game ver.commit 1.js
> +            }
만약 위 코멘트가 괜찮다면 이건 어떤가요? if문 쭉 나열된 부분을 아래와 같이 바꿀 수 있어보여요

```suggestion
            for (let i = 0; i < 7; i++) {
                if (x > (paddleX + paddleWidth) * i / 7 && x < (paddleX + paddleWidth) * (i + 1) / 7) {
                    dx = -dx;
                    dx = dx + Math.abs((0.05 * (3 - i)));   // 1.15, 1.10, 1.05, 1.00, 1.05, 1.10, 1.15배 x증가폭 변경
                    break;
                }
            }

```

2023-05-21 06:04 UTC, kth990303 commented on game ver.commit 1.js
> +let paddleWidth = 120;
개인적으로 레벨1부터 초기 길이 120은 좀 어려운 거 같은데...🥲
조금 더 늘리는건 어떻게 생각하시나요?

2023-05-21 06:32 UTC, Jiwoo-Seo commented on game ver.commit 1.js
> +            }
각도는 가운데 부분이어서 그렇게 했고, 이게 하다 보면 또 너무 빨라져서 가운데 구간은 속도를 조금 줄여주기로 했습니다.

2023-05-21 06:33 UTC, Jiwoo-Seo commented on game ver.commit 1.js
> +let paddleWidth = 120;
저도 하다보니까 80이 어려워서 120으로 했습니다... 아이템 구현중인데 패들을 늘려주는 기능이 있어서 120도 충분하더라구요.

2023-05-21 06:45 UTC, kth990303 commented on game ver.commit 1.js
> +let paddleWidth = 120;
아이템은 완전 랜덤이라, 게임 끝날때쯤에 패들 길이가 늘어나면 계속 어려운 상태로 가지 않을까 걱정이 되기도 하네요. 우선 진행해보고 추후에 고쳐보는걸로 하죠

2023-05-21 06:45 UTC, kth990303 commented on game ver.commit 1.js
> +            }
네 사실상 큰 문제는 없을 듯하긴 하네요

2023-05-21 06:46 UTC, kth990303 approved these changes
코멘트 확인했습니다. 충분히 이유가 있는 듯해서 approve했어요. 난이도야 사실상 추후에 다같이 플레이하면서 조정해도 될 듯합니다~

2023-05-23 05:31 UTC, KTIKTI approved these changes
괜찮습니다

크기 변화 기믹이 많이 껄끄러워서 없애도 될 것 같습니다

2023-05-23 05:39 UTC, Seo251 approved these changes

2023-05-25 15:41 UTC, kth990303 commented on game ver.commit 1.js
>  function move() {
가끔 `? 네모박스`에 맞아도 박스가 안깨지는 현상이 있어요. 심각한 버그까진 아니고 조금 의아할만한 버그 느낌이라, 플레이에 큰 영향을 주진 않을 듯하긴 해요.

해당 현상은 제가 내일 예비군 끝나고, 저녁에 동영상으로 카톡에 첨부할게요.
github issue에는 영상 첨부가 안되네요

2023-05-26 08:28 UTC, asdfjklec commented on game ver.commit 1.js
> +let itemCnt = 0;
주석 추가해 주시면 좋을 꺼 같아요

2023-05-26 08:28 UTC, asdfjklec commented on game ver.commit 1.js
>  } // 아이템 랜덤 배분 itemType 1~10까지, 깨질때마다 랜덤하게 배분
여기 if문이 왜 2개 필요한지 코멘트 적어주실 수 있을까요?

2023-05-26 08:28 UTC, asdfjklec commented on game ver.commit 1.js
> +    }
미해결오류 : level을 높이면서 블록 개수와 아이템 사용 횟수가 많아지면 아이템 창을 벗어나게 됩니다

2023-05-26 08:28 UTC, asdfjklec commented on game ver.commit 1.js
> +        dy = dy * 2;
해결 : 연속적으로 먹음 너무 커져서 1.35로 교체했습니다

2023-05-26 08:28 UTC, asdfjklec commented on game ver.commit 1.js
> +            paddledx = paddledx*0.66;
해결 : 배율 1.35로 바꿨습니다. 그리고 아이템창에 맞닿아 있을 때 커지면 아이템 창에 이미지가 그려져서 패들을 왼쪽으로만 커지게 바꿨습니다. 
미해결 오류 : 그럼에도 불구하고 이동할때 작게는 생깁니다.
질문 : 속도는 왜 늦추는지 몰라서 일단 지웠습니다.

2023-05-26 08:28 UTC, asdfjklec commented on game ver.commit 1.js
> +        dx = dx/2;
해결 : 여기도 배율 1.35로 변경했습니다

2023-05-26 08:28 UTC, asdfjklec commented on game ver.commit 1.js
>      }
미해결 오류 : 
유성이 움직이지 않고 순간이동해서 PosY로 맞았는지 판정하는것이 의미가 없어지는거 같습니다.  
유성 떨어지는 모습을 크게 보이고 그 위치에 패들이 있을 경우 즉발성으로 라이프가 감소 되는 방식이어야 if문이 효용이 있을 것 같습니다

2023-05-26 08:28 UTC, asdfjklec commented on game ver.commit 1.js
>              init();
제안 : life가 감소해 아이템 사용이 초기화 될 경우 아이템창에서 초기화된 아이템들은 삭제되어야 할 거 같습니다.

2023-05-27 01:10 UTC, kth990303 approved these changes
일부 버그들은 @asdfjklec 님이 수정한 PR로 진행될 것 같고, 진짜 중요한 버그들은 처리해놓았습니다.
approve하고 나머지 이슈들은 따로 이슈로 만들어서 PR올리는 방식으로 할게요

2023-05-27 01:10 UTC, merged