Feat/game logic
konkuk-galaxy/frontend pull request #25
Opened 2023-05-24 14:14 UTC by asdfjklec

closed #19 
closed #20 

game ver.commit 2.js
level2.html

2023-05-25 04:36 UTC, kth990303 requested changes
파일명이 잘못된 게 있는거같아서 request change로 남깁니다

2023-05-25 04:36 UTC, kth990303 commented on level2.html
> +  <script src="game next 1-1.js"> </script>
`game next 1-1.js`가 혹시 PR에 존재하나요? 
PC에서 돌려보는데 해당 파일이 없어서 에러가 발생하네요

<img width="1256" alt="image" src="https://github.com/konkuk-galaxy/frontend/assets/57135043/d4657f54-dabc-4958-9ede-8a8b6121ca1d">

우선 `game ver.commit 2.js`로 바꿔서 진행해볼게요

2023-05-25 04:36 UTC, kth990303 commented on game ver.commit 2.js
> +//patch 2 : html body에 p 태그 #col,row에서 행렬 개수 가져옴, 블록을 다 깼을 시 다음 단계로 넘어, 3단계 까지 갔을경우 end로 이동,
`patch 1`이 game ver.commit 1.js 이고, `patch 2`가 game ver.commit 2.js가 맞을까요?

레벨 1, 2 버전이 아닌 서로 다른 버전이라 생각하면 될까요? 레벨1에 비해 레벨2가 더 쉬워보인 거 같아 궁금해서 코멘트 남겨봅니다.

2023-05-25 07:49 UTC, asdfjklec commented on level2.html
> +  <script src="game next 1-1.js"> </script>
next1-1은 로컬에서 commit을 하느라 그렇습니다.
동일하게 진행해주시면 됩니다

2023-05-25 15:21 UTC, kth990303 commented on level2.html
> +  <script src="game next 1-1.js"> </script>
`next 1-1`이 올바르지 않다면 수정해서 push 날려주실 수 있을까요?
이대로 머지되면 저 사진처럼 NOT_FOUND가 발생하게 돼서요

2023-05-26 03:06 UTC, asdfjklec commented on level2.html
> +  <script src="game next 1-1.js"> </script>
commit 3로 추가패치 포함해서 올렸습니다
다시 pr 검토 해주세요

2023-05-27 01:13 UTC, kth990303 approved these changes
좋습니다 머지하겠습니다~

2023-05-27 01:14 UTC, merged