feat: 인게임 환경설정 구현 및 기믹 요소 관련 코드 변경
konkuk-galaxy/frontend pull request #34
Opened 2023-05-27 13:30 UTC by Seo251

close #21 
close #27 
close #37 
### 수정사항2
-레벨값이 계속 증가하는 문제가 애니메이션이 멈추지 않고 계속 로드되어서 발생하는 문제인 것 같음. flag == 1이 됐을때 애니메이션을 멈춰서 문제 해결

-------------------------------------------------------------------------------------------------------------------------------
### 수정사항
-패들의 위치를 초기화하는 함수가 위치를 옮기고 길이를 조정해서 길이가 늘어나있는 상태면 위치가 틀어짐. -> 길이를 조정하고 위치를 옮기게 함
-메인화면의 exit버튼을 없앰
-종종 레벨1 클리어시 엔딩화면으로 가는 버그 발생. 명확한 원인은 모르겠으나 level_info값이 증가할 때 문제가 발생한다고 판단되어 level_info값이 증가하는 코드를 모두 지우고 값을 대입하는 방식으로 바꿈.
-인게임 설정에서의 메인화면으로 이동하는 버튼 추가. 생상, 배경, bgm 정보등을 가지고 메인화면으로 되돌아감.

--------------------------------------------------------------------------------------------------------------------------------
인게임에서의 환경설정 구현
- html파일에 2개의 자바스크립트 파일을 적용해서 구현했습니다.(기존 게임 동작 js파일, setting.js파일)
- 메인에서의 설정창과 다르게 동작하는 부분들이 있어 setting.js파일로 따로 분리해서 코딩했습니다.
- 환경설정에서 설정한 공, 블럭의 색상 정보를 받아와 인게임에 적용되도록 했습니다.
- 인게임 설정창에 스테이지 다시시작 버튼을 만들고, 클릭시 스테이지동안 변경되었던 내역을 유지하면서 다시 시작되도록 했습니다.(관련 설명 아래에)
- 설정창이 띄워진 상태에서는 게임이 정지하도록 했습니다. 이후 방향키를 눌러도 인게임은 동작하지 않도록 했습니다.

인게임 코드(game ver.commit 3.js) 변경
- 게임을 시작했을 때 바로 실행되지 않고, 공이 막대위에 붙어서 정지화면으로 있다가 움직이면 움직이는 방향으로 공이 날라가면서 시작되도록 코드를 수정해 봤습니다. 오토플레이가 안되기 때문에 좌우키를 눌러서 게임이 시작될때 bgm도 실행되도록 했습니다.
- 공이 바닥에 떨어져서 초기화 될 때도 처음 시작처럼 멈췄다가 움직이면 시작되도록 수정해 봤습니다.
- draw() 코드가 2번 실행되는 걸로 확인했습니다. 공 속도가 느려서 그런 것 같던데, 게임을 멈추는 코드를 짜기 힘들어져 1개로 줄이고 dx, dy값을 *2시켰습니다.
- 레벨을 이동하는 부분을 수정했습니다. (관련 설명은 아래에)
  - 레벨 선택이나 다음 레벨로 이동시 파라미터 값들을 url 주소에 포함시켜 html 파일을 열고, html 파일이 열릴 때 정보들을 받아와 받은 정보들을 바탕으로 파일을 로드하도록 구현
  - 한 html파일에서 다른 html 파일로 넘어갈때 전 파일에서 다음 파일로 넘겨줘야 하는 값들을 url 주소에 포함시켜 건네주도록 했습니다. (레벨, 배경, 공 색상, 블럭 색상, bgm, 볼륨 정보)
  - 스테이지 다시시작 버튼도 기존 스테이지에서 변경되었던 정보를 가지고 url에 포함시켜 다시시작되도록 했습니다.

외에도 디테일한 부분들을 조금씩 추가해 봤습니다.

버그나 수정할 부분 있으면 알려주세요

2023-05-28 01:44 UTC, kth990303 requested changes
좋습니다
다만 레벨1 끝나고 레벨2로 가지지 않고 end.html 가지는 버그가 존재하는 듯한데, 확인 부탁드려요~

2023-05-28 01:44 UTC, kth990303 commented on setting.js
> +})
스테이지 다시 시작 기능 좋은 거 같아요.
설정 창 열었을 때, 메인화면으로 이동하는 기능도 추가로 있으면 좋을 듯합니다

2023-05-28 01:44 UTC, kth990303 commented on game ver.commit 3.js
>          }
가끔 레벨1이 끝났는데도 레벨2로 이동이 아닌, end.html로 바로 이동이 돼버리네요.
제생각엔 level_info가 엄청 빠르게 증가하다보니까 `level_info=2`로 증가해야되는데, 순식간에 레벨4로 가버린게 아닐까 싶어요. 리다이렉트 제외시켜보고 클리어해봤는데 level_info가 엄청 빠르게 증가하네요

<img width="501" alt="image" src="https://github.com/konkuk-galaxy/frontend/assets/57135043/b613ca4f-6dd7-4662-955b-2908468c415b">

2023-05-28 06:09 UTC, KTIKTI approved these changes
코드 변경 잘 보았습니다

2023-05-28 14:02 UTC, jray7890 approved these changes

2023-05-29 00:51 UTC, kth990303 approved these changes
LGTM

2023-05-29 00:51 UTC, merged