튜토리얼 추가
konkuk-galaxy/frontend pull request #39
Opened 2023-05-28 08:17 UTC by KTIKTI

close #24 
1. 튜토리얼 추가
2. main.html에서 난이도 선택후 tutorial.html로 이동, tutorial.html에서 level1.html, level2.html, level3.html로 이동
3. 난이도 변수 전송에 localstorage 이용

해야 할 부분이 있으면 말씀해 주세요

2023-05-28 10:01 UTC, kth990303 requested changes
튜토리얼 기능 아주 좋습니다 👍 
튜토리얼에도 스킵 기능이 있거나, 아니면 튜토리얼을 플레이할건지 물어봐주면 좋을 거 같은데 어떤가요?

2023-05-28 10:01 UTC, kth990303 commented on main.html
> +      <a href="tutorial.html" target="_self">hard</a>
강제로 튜토리얼로 넘어가기 전에, 튜토리얼을 플레이할건지 물어봐주면 어떨까요?
아니면 튜토리얼에도 스킵 버튼이 있으면 좋을 거 같아요

2023-05-28 10:25 UTC, KTIKTI commented
> 튜토리얼 기능 아주 좋습니다 👍 
> 튜토리얼에도 스킵 기능이 있거나, 아니면 튜토리얼을 플레이할건지 물어봐주면 좋을 거 같은데 어떤가요?

확인했습니다
곧 수정할때 만들겠습니다

2023-05-28 13:52 UTC, Jiwoo-Seo approved these changes
좋습니다!

2023-05-29 09:29 UTC, kth990303 approved these changes
기능 동작 확인했습니다.
코드 개선할수 있는 부분들 코멘트 달아봤습니다~

2023-05-29 09:29 UTC, kth990303 commented on tutorial.js
> +            location.href="level3.html?level_info=3"
아래와 같이 한 줄로 줄일 수도 있을 듯하네요
```suggestion
            location.href = `level${difficulty}.html?level_info=${difficulty}`;
```

2023-05-29 09:29 UTC, kth990303 commented on tutorial.js
> +        $("img").attr("src", "tutorial/960x540image3.png");
`$("img").attr("src", `tutorial/960x540image.png`);` 코드가 매 index마다 달라져야돼서 반복이 돼고 있네요.


`$("img").attr("src", `tutorial/960x540image${index + 1}.png`);`로 넣으면 코드 반복을 줄일 수 있을 거 같아요.
<img width="765" alt="image" src="https://github.com/konkuk-galaxy/frontend/assets/57135043/035546ef-4d7b-45bb-982a-5e24358f2a31">

2023-05-29 09:29 UTC, kth990303 commented on game ver.commit 3.js
> +let scorestr = infostr + score + "점";
점수가 설명 옆에 있어서 비교적 눈에 띄지 않는 듯 보여요.
<img width="808" alt="image" src="https://github.com/konkuk-galaxy/frontend/assets/57135043/7e93f82a-02f4-4a2e-af43-b58bef2d9ce0">
우측 상단에 점수를 크게 표시하는 건 어떻게 생각하세요?

2023-05-29 09:35 UTC, kth990303 reviewed
추가로, 현재 게임에서 지고 엔딩화면을 본 뒤에 뒤로가기를 하면 점수가 그대로 유지돼요.
뒤로가기를 막거나, 점수를 초기화하는 로직이 필요할 듯해요

2023-05-29 09:59 UTC, Seo251 requested changes
메인에서 설정한 설정 정보가 level1에서 적용이 안되는 버그가 있습니다

2023-05-29 10:14 UTC, asdfjklec reviewed
50점 이상이 되면 바로 게임이 종료되고 승리로 넘어가는데 괜찮나요?

2023-05-29 10:14 UTC, asdfjklec reviewed
50점 이상이 되면 바로 게임이 종료되고 승리로 넘어가는데 괜찮나요?

2023-05-29 10:41 UTC, kth990303 commented
@asdfjklec 
튜토리얼 페이지에서 보면 Easy는 50점, Normal은 100점, Hard는 200점 이상이면 Victory로 게임 종료를 의도한 것 같습니다.

2023-05-29 15:06 UTC, KTIKTI commented
> 추가로, 현재 게임에서 지고 엔딩화면을 본 뒤에 뒤로가기를 하면 점수가 그대로 유지돼요. 뒤로가기를 막거나, 점수를 초기화하는 로직이 필요할 듯해요

이미 엔딩을 본 상황이라 굳이 막지는 않았습니다

2023-05-29 18:21 UTC, KTIKTI commented
@kth990303 
main 브랜치 머지 했습니다
이대로 pull 해도 좋을 것 같습니다

2023-05-30 00:26 UTC, kth990303 commented
머지하겠습니다. 수고하셨어요

2023-05-30 00:26 UTC, merged